myapp/__init__.py
from flask import Flask, render_template
#ExtDeprecationWarning: Importing flask.ext.bootstrap is deprecated, use flask_bootstrap instead.
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager


bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def creat_app():
	app = Flask(__name__)
	app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:zhangtao@localhost/project'
	app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
	app.config['SECRET_KEY'] = '\xf8%\x9b\xd9\xb2a\xeam\xc96\xdf\x9dn\xc9\xfdH\xc8n\xff\xf3:\xf9\xb4\xac'

	bootstrap.init_app(app)
	db.init_app(app)
	login_manager.init_app(app)
	
	from .views.index import index
	app.register_blueprint(index, url_prefix='/app')

	from .auth import auth as auth_blueprint
	app.register_blueprint(auth_blueprint, url_prefix='/auth')

	@app.errorhandler(404)
	def page_not_found(e):
		return render_template('404.html')

	@app.errorhandler(500)
	def internal_server_error(e):
		return render_template('500.html')
	
	return app

myapp/views/index.py
from flask import Blueprint, render_template, flash, redirect, url_for, jsonify, request
from ..modules import Words, Translates
from .. import db
from flask_login import login_required

index = Blueprint('index', __name__)

@index.route('/index')
@login_required
def index_page():
	return '<h2>Hello</h2>'
'''
@index.route('/words-list')
def query_all():
	word_dict = {}
	words_list = Words.query.all()
	for word in words_list:
		trans = Translates.query.filter_by(word_id=word.id).all()
		word_dict[word] = trans

	return render_template('index.html', words=word_dict)
'''
@index.route('/words-list')
def query_all():
	words_list = Words.query.all()
	return render_template('index.html', words=words_list)


@index.route('/delete/<int:id>')
def delete_word(id):	
	translates = Translates.query.filter_by(word_id=id).all()
	for translate in translates:
		db.session.delete(translate)

	word = Words.query.filter_by(id=id).first_or_404()
	db.session.delete(word)

	db.session.commit()
	flash('delete successfully!')
	return redirect(url_for('index.query_all'))

@index.route('/page-test')
def show_page():
	return render_template('page.html')

@index.route('/detail/<int:id>', methods=['GET',])
def word_detail(id):
	tasks = []
	trans = Translates.query.filter_by(word_id=id).all()
	for translate in trans:
		tasks.append(translate.Translate)
	return jsonify({'task':tasks})

myapp/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block head %}
{{ super() }}
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{{ url_for('index.index_page') }}">Hello</a>
		</div>
	</div>
</div>
{% endblock %}

myapp/templates/index.html
{% extends "base.html" %}

{% block title %}Index{% endblock %}

{% block content %}
<h1>Words List</h1>
<hr/>

{% if words %}
	{% for item in words %}
		<div>
			<h3>{{item.word}}</h3>
			<a href=# id="detail" class="btn btn-info" role="button">detail</a>

			<a href="{{ url_for('index.delete_word', id=item.id)}}" \
				class="btn btn-info" role="button">delete</a>
		</div>			
		<hr/>
	{% endfor %}

	
{% endif%}

{% endblock %}

{% block scripts %}
{{super()}}
<script type="text/javascript">
$(function(){

	method_get = function(event){
		var docu = this
		
		$.get("{{url_for('index.word_detail', id=4)}}", function(data, status){
			
			if(status == 'success')
			{
				$(docu).parent().append(data.task);
			}
			else
			{
				alert("Data: " + data.task);
			}
		});
	};

	method_ajax = function(){
		$.ajax({type:'GET', url:"{{url_for('index.word_detail', id=4)}}",
			success:function(data, textStatus){
				$(this).parent().hide();
			},
			error: function(XMLResponse) {  
                alert(XMLResponse.responseText)  
            }
		})
	};

	method_test = function(){
		$(this).parent().hide();
	};

	$('a#detail').click(method_get);
});
</script>
{% endblock%}

myapp/templates/login.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="page-header">
	<h1>Login</h1>
</div>
<div class="col-md-4">
	{{ wtf.quick_form(form) }}
</div>
{% endblock %}

myapp/templates/page.html
{% extends "bootstrap/base.html" %}

{% block title %}Page-test{% endblock %}

{% block head %}
{{ super() }}
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-inverse" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="#">Page</a>
		</div>

		<div class="nav navbar-nav">
			<li class="active"><a href="#">IOS</a></li>
			<li><a href="#">SVN</a></li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					Java
					<b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><a href="#">jmeter</a></li>
                    <li><a href="#">EJB</a></li>
                    <li><a href="#">Jasper Report</a></li>
                    <li class="divider"></li>
                    <li><a href="#">分离的链接</a></li>
                    <li class="divider"></li>
                    <li><a href="#">另一个分离的链接</a></li>
				</ul>
			</li>
		</div>
	</div>

</nav>
{% endblock %}

myapp/templates/registe.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Registe{% endblock %}

{% block content %}

<div class="page-header">
	<h1>Registe</h1>
</div>
<div class="col-md-4">
	{{ wtf.quick_form(form) }}
</div>
{% endblock %}